-- models/staging/stg_products.sql

SELECT
    -- Product name/title
    PRODUCT_TITLE,

    -- Number of items sold for this product
    ITEMS_SOLD,

    -- Net revenue generated by this product
    NET_REVENUE,

    -- Total number of orders containing this product
    ORDERS,

    -- Product category or classification
    CATEGORY,

    -- Number of variations (e.g., size or color options)
    VARIATIONS,

    -- File source and load timestamp metadata
    FILENAME,
    LOAD_TIMESTAMP

-- Pull data from raw_products source table
FROM {{ source('raw', 'raw_products') }}
